### ISSUE TITLE
Modifications

### ISSUE THREAD

**Issue by hashmeet02** [yemregumus/PRJ566-Team-3#5]
- [x] add explanation for tasks, reminder, habits - @yemregumus 
- [x] adding 5 business rules- @yemregumus 
- [x] adding more functionalities ( activity diagram, mockup, use case diagram, use case description)
  - [x] Update a habit - @busycaesar 
  - [x] Delete a calendar event - @busycaesar 
  - [x] view reminders- @hashmeet02 
  - [x] view habits- @hashmeet02 
  - [x] View tasks - @hashmeet02 
  - [x] View Profile- @okuti2 
  - [x] Calendar View- @okuti2
- [x] Reorder functionalities. - @okuti2 
- [x] Add a note to explain all functionalities work the same way for different things- task, reminders, habits etc. - @okuti2

**Comment by yemregumus** [comment]
added my parts please review and let me know if any further updates are required.

**Comment by hashmeet02** [comment]
added activity diagrams and use case descriptions for view a reminder, tasks and habits use cases.

**Comment by okuti2** [comment]
assigned myself task

**Comment by okuti2** [comment]
added notes and reordered functionality based on user exprience

**Comment by okuti2** [comment]
added functionalities for calendar and profile view

**Comment by busycaesar** [comment]
Done!
