### ISSUE TITLE
Week-8

### ISSUE THREAD

**Issue by hashmeet02** [yemregumus/PRJ566-Team-3#7]
- [x] problem statement - @yemregumus 
- [x] product vision - @hashmeet02 
- [x] create a task through intelliWand - @hashmeet02 
- [x] create a task manually- @okuti2 
- [x] Profile view- @yemregumus 
- [x] Home Page - @okuti2 
- [x] Update a Habit - @busycaesar

**Comment by okuti2** [comment]
Done adding slides and recording

**Comment by yemregumus** [comment]
Done my portion, open to discussion if there is any spark for improvement.
