### ISSUE TITLE
Week 11 Presentation

### ISSUE THREAD

**Issue by yemregumus** [yemregumus/PRJ566-Team-3#9]
- [x] Yunus Slide Numbers 1,2,3,9,10,11,12,13
- [x] Hasmeet Slide Numbers 4,5,6,7,8
- [x] Toyosi Slide Numbers 14,15,16,17,18,19,20
- [x] Dev Slide Numbers 21,22,23,24

Please provide scripts in the slide notes in each slide

**Comment by hashmeet02** [comment]
Add a task slides are done.

**Comment by yemregumus** [comment]
My portion of slides have their script now.

**Comment by busycaesar** [comment]
Add script!
